export const TOKENS = {
  // Services
  AuthService: Symbol.for('AuthService'),
  UserService: Symbol.for('UserService'),
  RestaurantService: Symbol.for('RestaurantService'),
  BranchService: Symbol.for('BranchService'),
  MemberService: Symbol.for('MemberService'),
  ProductService: Symbol.for('ProductService'),
  CustomerAddressService: Symbol.for('CustomerAddressService'),
  PermissionCacheService: Symbol.for('PermissionCacheService'),
  OrderService: Symbol.for('OrderService'),
  PaymentService: Symbol.for('PaymentService'),
  KashierWebhookService: Symbol.for('KashierWebhookService'),
  AssignmentService: Symbol.for('AssignmentService'),
  PresenceService: Symbol.for('PresenceService'),
  SettlementService: Symbol.for('SettlementService'),
  FinanceService: Symbol.for('FinanceService'),
  AgentService: Symbol.for('AgentService'),

  // Controller
  AuthController: Symbol.for('AuthController'),
  UserController: Symbol.for('UserController'),
  RestaurantController: Symbol.for('RestaurantController'),
  BranchController: Symbol.for('BranchController'),
  MemberController: Symbol.for('MemberController'),
  ProductController: Symbol.for('ProductController'),
  CustomerAddressController: Symbol.for('CustomerAddressController'),
  OrderController: Symbol.for('OrderController'),
  WebhookController: Symbol.for('WebhookController'),
  AssignmentController: Symbol.for('AssignmentController'),
  FinanceController: Symbol.for('FinanceController'),
  AgentController: Symbol.for('AgentController'),

  // Lib/infra/
  Logger: Symbol.for('Logger'),
  CacheProvider: Symbol.for('CacheProvider'),
  EmailProvider: Symbol.for('EmailProvider'),
  WsServer: Symbol.for('WsServer'),
  KashierProvider: Symbol.for('KashierProvider'),
};
